webapp/accounts/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login,logout
from django.views.generic import ListView, DetailView
from .models import PatientProfile as Patient
from django.contrib.auth.models import User

urlpatterns = [
    path('',views.home,name ='home'),
    path('login/',login,{'template_name':'accounts/login.html'},name='login'),
    path('logout/',logout,{'template_name':'accounts/logout.html'},name='logout'),
    path('register/',views.register,name='register'),
   	url(r'^profile/$',views.view_profile,name='view_profile'),
   	url(r'^profile/edit/$',views.edit_profile,name='edit_profile'),
	  url(r'^profile/(?P<pk>\d+)/$', views.view_profile, name='view_profile_with_pk'),
   	url(r'^patientlist/$',views.patientlist,name ='patientlist'),
   	]

webapp/home/urls.py
from django.urls import path
from django.conf.urls import url
from home.views import HomeView

urlpatterns = [
    path('',HomeView.as_view(),name ='home')
]

webapp/webapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings 
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^accounts/',include(('accounts.urls','accounts'),namespace='accounts')),
    url(r'^home/',include(('home.urls','home'),namespace='home'))
    	]

webapp/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.core.validators import MaxValueValidator

# Create your models here.
class UserProfileManager(models.Manager):
	def get_queryset(self):
		return super(UserProfileManager,self).get_queryset().filter()
		
class PatientProfile(models.Model):
	user = models.OneToOneField(User,on_delete = models.CASCADE)
	
	def __str__(self):
		return self.user.username	
def create_profile(sender, **kwargs):
	if kwargs['created']:
		Patient_profile =PatientProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile,sender = User)

webapp/home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
	user = models.ForeignKey(User,on_delete = models.CASCADE)
	medicines = models.CharField(max_length = 500)
	created = models.DateTimeField(auto_now_add = True)
	log = models.CharField(max_length = 500)

webapp/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
import datetime


class RegistrationForm(UserCreationForm):
	gender = forms.ChoiceField(choices=(('M','Male'),('F','Female')))
	age = forms.IntegerField(required= True,max_value=100,min_value = 1)
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields =(
			'username',
			'first_name',
			'last_name',
			'gender',
			'age',
			'email',
			'password1',
			'password2',
			)


	def save(self, commit=True):
		user= super(RegistrationForm, self).save(commit=False)
		user.username = self.cleaned_data['username']
		user.first_name = self.cleaned_data['first_name']
		user.last_name = self.cleaned_data['last_name']
		user.gender = self.cleaned_data['gender']
		user.age = self.cleaned_data['age']
		user.email = self.cleaned_data['email']

		if commit:
			user.save()

		return user

class EditProfileForm(UserChangeForm):

	class Meta:
		model = User
		fields = ('email','first_name','last_name','password')

webapp/home/forms.py
from django import forms
import datetime
from .models import Post
class LogForm(forms.ModelForm):
	medicines = forms.CharField(label='Medicines',widget=forms.TextInput(
																			attrs={
																					'class':'form-control',
																					'placeholder':'Medicines'}
																					))
	log = forms.CharField(label='Log',widget=forms.TextInput(
																attrs={
																'class':'form-control',
																'placeholder':'Type the checkup log here...'
																}))


	class Meta:
		model = Post
		fields =('medicines','log',)

webapp/accounts/views.py
from django.shortcuts import render,redirect
from .forms import RegistrationForm,EditProfileForm
from home.forms import LogForm
from django.contrib.auth.forms import UserChangeForm
from home.models import Post
from django.contrib.auth.models import User

# Create your views here.

def home(request):
	return render(request,'accounts/home.html')

def login_redirect(request):
	return redirect('/accounts/')

def register(request):
	if request.method =='POST':
		form = RegistrationForm(request.POST) 
		if form.is_valid():
			form.save()
			return redirect('/accounts/')
	else:
		form = RegistrationForm()
		args ={'form': form}
		return render(request,'accounts/reg_form.html',args)


def view_profile(request, pk=None):
    if pk:
        user = User.objects.get(pk=pk)
        posts = Post.objects.all().order_by('-created').filter(user_id=user.id)
        args = {'form':LogForm,'user':user,'posts':posts}
        if request.method=='POST':
        	form = LogForm(request.POST)
        	if form.is_valid():
        		post = form.save(commit = False)
        		post.user = user
        		post.save()
        		medicines = form.cleaned_data['medicines']
        		log = form.cleaned_data['log']
        		form =LogForm()
        	return redirect('accounts:patientlist')
        return render(request,'accounts/profile.html',args)
    else:
        user = request.user
        args ={'user': user}
        return render(request, 'accounts/profile.html', args)

def patientlist(request):
	user=User.objects.all().filter(is_staff=False)
	args = {'user':user}
	return render(request,'accounts/patientlist.html',args)

	
def edit_profile(request):
	if request.method=='POST':
		form = EditProfileForm(request.POST, instance = request.user)

		if form.is_valid():
			form.save()
			return redirect('/accounts/profile/')
	else:
		form = EditProfileForm(instance=request.user)
		args = {'form':form}
		return render(request,'accounts:edit.html',args )

webapp/home/views.py
from django.views.generic import TemplateView
from django.shortcuts import render
from home.forms import LogForm
from django.contrib.auth.models import User
from home.models import Post


class HomeView(TemplateView):
	template_name = 'accounts/profile.html' #homepage for homeapp

	def get(self, request):
		form = LogForm()
		user = User.objects.all().filter(is_staff=False )
		posts= Post.object.all().order_by('-created')

		return render(request,self.template_name,{'form': form,'users':user,'posts':posts})

	def post(request):
		if request.method=='POST':
			form = LogForm(request.POST, instance = request.user)

			if form.is_valid():
				post = form.save(commit = False)
				post.user = request.user
				post.save()
				medicine = form.cleaned_data['medicine']
				log = form.cleaned_data['log']

				form =LogForm()
				return HttpResponseRedirect("")

			args = {'form':form}
			return render(request,self.template_name,args )

webapp/webapp/views.py
from django.shortcuts import redirect

webapp/accounts/templates/accounts/edit.html
{% extends 'base.html' %}


	{% block head %}
		<div class="container">
			<h1> Edit Profile <a href="{% url 'accounts:edit_profile' %}"> </h1>
		</div>
	{% endblock %}

	{% block body %}

		<div class="container">
			<form method="post">
				{% csrf_token %}
				{{form.as_p}}
				<button type = "submit">Submit</button>
			</form>
		</div>

	{% endblock %}

webapp/accounts/templates/accounts/home.html
{% extends 'base.html' %}

	{% block body %}
		<div class="container-fluid">
			<h2> WELCOME </h2>
		</div>
	{% endblock %}

webapp/accounts/templates/accounts/login.html
{% extends 'base.html' %}

	{% block body %}
	<h1>Welcome</h1>
	<p>
		You can log in here
	</p>
	<div class="container-fluid">
		<h2>login</h2>
		<form method="post">
			{% csrf_token %}
			{{form.as_p}}
			<button type = "submit">Login</button>
		</form>
	</div>
	{% endblock %}
	

webapp/accounts/templates/accounts/logout.html
{% extends 'base.html' %}

	{% block body %}

		<div class="container">
			<h4> You have logged out. </h4>
			<h3>Go back to <a href="{% url 'accounts:home' %}">HOME</a></h3>
		</div>

	{% endblock %}

webapp/accounts/templates/accounts/patientlist.html
{% extends 'base.html' %}

{% block head %}
	<div class="container">
		<h1>Patient List</h1>
	</div>
{% endblock%}

{% block body %}
	<div class='table-responsive' >
	<table class = 'table'>
	<tr>
		<th>FirstName</th>
		<th>LastName</th>
		<th>Add report</th>
	</tr>
	{% for person in user %}	
	<tr>	
			<td>{{ person.first_name }}</td>
			<td>{{ person.last_name }}</td>
			<td><a href="{% url 'accounts:view_profile_with_pk' pk=person.pk %}"><button class="btn btn-primary">Add session</button></a></td>
	</tr>
	{% endfor %}
	</table>
	</div>
{% endblock%}

webapp/accounts/templates/accounts/profile.html
{% extends 'base.html' %}


	{% block head %}
		<div class="container">
			<h1> Profile </h1>
		</div>
	{% endblock %}
	{% block nav %}
		<li><a href="{% url 'accounts:patientlist' %}"><span class="glyphicon glyphicon-user"></span>Patientlist</a>
	{% endblock%}

	{% block body %}

		<div class="col-md-8">
			<p>
				<p>Username:{{user}}</p>
				<p>FirstName:{{ user.first_name }}</p>
				<p>LastName:{{ user.last_name }}</p>
				<p>Email:{{ user.email }}</p>
				<p>Gender:{{ user.gender.value }}</p>
			</p>
		</div>
	{% endblock %}

 

	{% block log %}
	<div class="container">
		<h1>Add Log</h1>
		<form method="post">
			{% csrf_token %}
			{{form.as_p}}
			<br>
			<button type = "submit">Submit</button>
		</form>
	</div>
	<br>
	<div class = "container">
	<h1>History</h1>
	{% if posts %}
	        {% for post in posts %}
	        <hr class='line'>
	        <div class = "row">
	        	<span class="col-sm-6" style="font-size:30px;font-weight:bold;"}>Session {{post.id}} </span>
	        	<span class="col-sm-6" align='right'>{{ post.created }}</span>
	        </div>
	    <div class='container'>
	        <h3>Log</h3>
            <p>{{ post.log }}</p>
            <hr>
            <h3>Medicines</h3>
            <p>{{ post.medicines }}</p>
        </div>
        {% endfor %}
        	
    {% else %}
    	<h3> No recent History</h3>
    	</div>
    {% endif %}
	{% endblock %}

webapp/accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}
	{% block body %}
	<div class="container">
		<h1>Register</h1>
		<form method="post">
			{% csrf_token %}
			{{form.as_p}}
			<button type = "submit">Submit</button>
		</form>
	</div>
	{% endblock %}

webapp/accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>DigitizedCheckupLog</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% load static %}
  <link rel="stylesheet" href="{% static 'accounts/bootstrap.min.css' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="{% static 'accounts/bootstrap.min.js' %}"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
  hr.line {
  background-color: black;
  width: 100%;
  height: 1px;
  border-top: 1px black
  }  
  </style>
</head>
<body>
<nav class="navbar navbar-inverse">
      {% if user.is_authenticated %}
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'accounts:home' %}">DigitizedCheckupLog</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li  class ="active"><a href= "{% url 'accounts:home' %}">Home</a></li> 
      {% block nav %}

      {% endblock %}
      <li><a href="{% url 'accounts:logout' %}"><span class="glyphicon glyphicon-user"></span> Log out</a>
    </ul>
  </div>

  {% else %}

  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'accounts:home' %}">DigitizedCheckupLog</a>
      <a class="navbar-brand" href= "{% url 'accounts:home' %}"> Home</a>
    </div>
    <ul class="nav navbar-nav navbar-right">   
      <li><a href="{% url 'accounts:login' %}" > <span class="glyphicon glyphicon-log-in"> </span>Login</a> </li> 
    </ul>
  </div>
  {% endif %}

</nav>
 <div class="container">
  {% block head %}

  {% endblock %}
</div> 
<div class="container">
  {% block body %}

  {% endblock %}
</div>
<div class="container">
  {% block log %}

  {% endblock %}
</div>
</body>
</html>

webapp/home/templates/home/home.html
{% extends 'base.html' %}


{% block head %}
	<div class="container">
		<h1>Patient List</h1>
	</div>
{% endblock%}

{% block body %}

	<div class='table-responsive' >
	<table class = 'table'>
	<tr>
		<th>FirstName</th>
		<th>LastName</th>
		<th>Add report</th>
	</tr>
	{% for person in users %}	
	<tr>	
			<td>{{ person.first_name }}</td>
			<td>{{ person.last_name }}</td>
			<td><a href="{% url 'accounts:view_profile_with_pk' pk=person.pk %}"><button class="btn btn-primary">Add session</button></a></td>
	</tr>
	{% endfor %}
	</table>
	</div>
{% endblock%}